class Exception_array(Exception):
    pass